// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WSvdwKxw3Pia4LbUc9FpurpQ1twOym0',
    appId: '1:1089193281809:android:c8832ab4fc2fb51315e4b0',
    messagingSenderId: '1089193281809',
    projectId: 'chatappstor',
    storageBucket: 'chatappstor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq4fCHCr4n4GlKV0XoQQ84l0s26F_jqwY',
    appId: '1:1089193281809:ios:5512a7cff9e331e215e4b0',
    messagingSenderId: '1089193281809',
    projectId: 'chatappstor',
    storageBucket: 'chatappstor.firebasestorage.app',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXALWjVneGCXxVZSTF4sRTrqCJfU146xE',
    appId: '1:1089193281809:web:52cde21e51c3bcea15e4b0',
    messagingSenderId: '1089193281809',
    projectId: 'chatappstor',
    authDomain: 'chatappstor.firebaseapp.com',
    storageBucket: 'chatappstor.firebasestorage.app',
    measurementId: 'G-7YMM8QW6RE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXALWjVneGCXxVZSTF4sRTrqCJfU146xE',
    appId: '1:1089193281809:web:52cde21e51c3bcea15e4b0',
    messagingSenderId: '1089193281809',
    projectId: 'chatappstor',
    authDomain: 'chatappstor.firebaseapp.com',
    storageBucket: 'chatappstor.firebasestorage.app',
    measurementId: 'G-7YMM8QW6RE',
  );

}